/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://yqxeilto5ncpzkser2p2figgju.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2p2j64x4wbgslh2qiuitny733e",
    "aws_cognito_identity_pool_id": "ap-south-1:8adfab35-f971-4c13-b8a3-66a38b9de0b8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_XlZqyYw9x",
    "aws_user_pools_web_client_id": "7t8mdfciod33d2rrk1gpiv4qh7",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "aakaars-storage-100164035-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
